exports.vals = {
	confirmEmails: {
		from: "no-reply@test-app.com"
	},
	dbList: {
		mysql_project_db: 'redoq_db'
	},
	validDbs: [
		'mysql_project_db'
	],
	clientIp: '',
	defaultDB: 'mysql_bpr',
	tz: 'Asia/Kolkata',
	hash_key: '',
	auth_key: '',
	app_env: 'PROD',
	FIREBASE_API_KEY: 'AIzaSyDVPHjZwCXmiMVUps0MucNzYko9a-AGcWQ',
	appUrl: 'http://localhost:3000/api/webapi',
	frontEndFilePath: 'http://localhost:3000/apiService/',
	frontEndUserProfilePath: 'http://localhost:3000/userProfile/',
	optLength: 6,
	otpExpireMinutes: 5,
	routes: {
		policeAssistance: 'policeAssistance',
		callBackup: 'callBackup'
	},
	host: '',
	origin: '',
	login_user: {},
	dbconn: '',
	customer: {},
	service_name: "apiservice",
	regex: {
		phone_number: /^[6-9]\d{9}$/,
		postcode_regex: /^(GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\d[\dA-Z]?[ ]?\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\d{1,4})$/i,
		alpha_space: /^[\pL\s]+$/,
		card_security_code: /^\d{3,4}/,
		cardholder_name: /^[a-zA-Z 0-9&-.']{1,50}/,
		card_expiry: /^(0[1-9]|1[012])\d{2}/,
	},
	encKeys: {
		DEV: {
			"k1": "",
			"k2": ""
		},
		PROD: {
			"k1": "",
			"k2": ""
		}
	},
	secretKeys: {
		DEV: {
			"APISERVICE": "462D4A61eqweqweqweq87032733576-APISERVICE-2443264629eqweqweqweqwe6556A586E32",
		},
		PROD: {
			"WEBSERVICE": "68566D5971eqweqweqwe7A24432646-AS-367556B5870327335czxczczx452848",
		}
	},
	sms: {
		"Nexmo": {
			"api_key": "3clgkgg5f",
			"api_secret": "kXewSsr",
			"url": "https://rest.nexmo.com/sms/json"
		}

	},
	socket: {
		Pusher: {
			app_id: "105",
			app_key: "472a6812d",
			app_secret: "d462a",
			useTLS: true,
			cluster: "eu"
		},
	},
	email: {
		Mailgun: {
			'api': {
				'endpoint': 'api.eu.mailgun.net',
				'version': 'v3',
				'ssl': true
			},
			'from': {
				'address': 'mail@noreply.dineorder.com',
				'name': 'RedoQ',
			},
			force_from_address: false,
			app_key: "6e4eaac",
			public_api_key: 'pubkey',
			domain: 'noreply.dineorder.com',
		},
	},
	push_notification: {
		firebase: {
			url: "https://fcm.googleapis.com/fcm/send",
			key_app: "muysb51fhrUa_",
		},
		onesignal: {
			url: "https://onesignal.com/api/v1/notifications",
			key_app: {
				key: "muysb51fhrUa_",
				app_id: "e237",
				android_channel_id: "d9f72"
			}
		}
	},
	apiurl: {
		webservice: "https://webservice.redoq.com"
	},
	payment_gateway: {
		stripe: {
			PROD: {
				payment_gateway_Code: '1003',
				publishable_key: "pk",
				secret_key: "sk",
				api_url: "https://api.stripe.com"
			},
			DEV: {
				payment_gateway_Code: '1003',
				publishable_key: "pk",
				secret_key: "sk",
				api_url: "https://api.stripe.com"
			}
		},
	},
	payment_gateway_alias: {
		'Stripe India': 'stripeIN'
	},
	awssdk: {
		DEV: {

		},
		PROD: {

		}
	},
	defaults: {
		sms: {
			loginOtp: "thesmsworks-transactional"
		},
		socket: {
			orders: "Pusher"
		}
	},
	districtList: ['West Bengal District', 'Gujarat District', 'Belize District', 'Cayo District', 'Corozal District', 'Orange Walk District', 'Stann Creek District', 'Toledo District'],
	cityList: {
		'Belize District': [
			'Bermudian Landing',
			'Biscayne',
			'Burrell Boom',
			'Bomba',
			'Boston',
			'Burrell Boom',
			'Caye Caulker',
			'Corozalito',
			'Crooked Tree',
			'Double Head Cabbage',
			'Flowers Bank',
			'Freetown Sibun',
			'Gales Point',
			'Gardenia',
			'Gracie Rock',
			'Hattieville',
			'Isabella Bank',
			'La Democracia',
			'Ladyville',
			'Lemonal',
			"Lord's Bank",
			'Lucky Strike',
			'Mahogany Heights',
			'Maskall',
			'May Pen',
			'Mile 25 Village',
			'Rancho Dolores',
			'Rock Stone Pond',
			'San Pedro',
			'Sandhill',
			'Santana',
			'Scotland Halfmoon',
			"St. Ann's",
			"St. George's Caye",
			"St. Paul's Bank",
			"Western Paradise/West Lake/8 Miles",
			"Willows Bank"
		],
		'Cayo District': [
			'Armenia',
			'Belmopan',
			'Benque Viejo del Carmen',
			'San Ignacio',
			'Santa Elena',
			"Arenal",
			"Lower Barton Creek",
			"Billy White",
			"Blackman Eddy",
			"Branch Mouth",
			"Buena Vista",
			"Bullet Tree Falls",
			"Calla Creek",
			"Camalote",
			"Central farm",
			"Cotton Tree",
			"Cristo Rey",
			"Duck Run I",
			"Duck Run II",
			"Duck Run III",
			"Esperanza",
			"Franks Eddy",
			"Georgeville",
			"La Gracia",
			"Los Tambos",
			"More Tomorrow",
			"Ontario",
			"Paslow Falls/Plant",
			"Roaring Creek",
			"Ringtail Village",
			"San Antonio",
			"San Jose Succotz",
			"San Marcos",
			"Santa Familia",
			"Santa Marta",
			"Santa Rosa",
			"Santa Teresita",
			"Selena",
			"Seven Miles",
			"Spanish Lookout",
			"Springfield",
			"St. Matthews",
			"Teakettle",
			"Unitedville",
			"Upper Barton Creek",
			"Valley of Peace",
			"Yalbac"
		],
		'Corozal District': [
			'Corozal Town',
			'Altamira',
			'Buena Vista',
			'Calcutta',
			'Caledonia',
			'Carolina',
			'Chan Chen',
			'Chunox',
			'Concepción',
			'Consejo',
			'Copper Bank',
			'Cristo Rey',
			'Estrella',
			'Libertad',
			'Little Belize',
			'Louisville',
			'Paraiso',
			'Patchakan',
			'Progresso',
			'Ranchito',
			'San Andrés',
			'San Antonio',
			'San Joaquín',
			'San Narciso',
			'San Pedro',
			'San Román',
			'San Víctor',
			'Santa Clara',
			'Sarteneja',
			'Xaibe',
			'Yo Chen'
		],
		'Orange Walk District': [
			'Orange Walk Town',
			'August Pine Ridge',
			'Blue Creek',
			'Carmelita',
			'Chan Chich',
			'Chan Pine Ridge',
			'Cuatro Leguas',
			'Douglas',
			'Fire Burn',
			'Guinea Grass',
			'Honey Camp',
			'Indian Church',
			'Indian Creek',
			'Indian Hill Estate',
			'Petville',
			'Richmond Hill',
			'San Antonio',
			'San Carlos',
			'San Estevan',
			'San Felipe',
			'San José',
			'San José Palmar',
			'San Juan',
			'San Lorenzo',
			'San Lázaro',
			'San Luis',
			'San Pablo',
			'San Román',
			'Santa Cruz',
			'Santa Marta',
			'Shipyard',
			'Sylvestre Camp',
			'Tower Hill',
			'Tres Leguas',
			'Trial Farm',
			'Trinidad',
			'Yo Creek'
		],
		'Stann Creek District': [
			'Dangriga',
			'Alta Vista',
			'Cow Pen',
			'George Town',
			'Hope Creek',
			'Hopkins',
			'Hummingbird Community',
			'Independence',
			'Kendal',
			'Mango Creek',
			'Maya Beach',
			'Maya Center',
			'Maya Mopan',
			'Middlesex',
			'Mullins River',
			'Placencia',
			'Pomona',
			'Red Bank',
			'Riversdale',
			'San Juan',
			'San Román',
			'Santa Cruz',
			'Santa Rosa',
			'Sarawee',
			'Seine Bight',
			'Silk Grass',
			'Sittee River',
			'South Stann Creek',
			'Steadfast',
			'Valley Community'
		],
		'Toledo District': [
			'Punta Gorda',
			'Aguacate',
			'Barranco',
			'Bella Vista',
			'Big Falls',
			'Bladden',
			'Blue Creek',
			'Boom Creek',
			'Cattle Landing',
			'Conejo',
			'Corazon',
			'Crique Jute',
			'Crique Largo',
			'Crique Sarco',
			'Crique Trosa',
			'Dolores',
			'Dump',
			'Elridge',
			'Forest Home',
			'Golden Stream',
			'Graham Creek',
			'Hicattee',
			'Hicattee Southern Highway',
			'Indian Creek',
			'Jacinto/Westmoreland',
			'Jalacte',
			'Jordan',
			'Laguna',
			'Mabilha',
			'Mafredi',
			'Mango Walk',
			'Medina Bank',
			'Midway',
			'Monkey River',
			'Moody Hill',
			'Na Luum Ca',
			'New Road Area',
			'Otoxha',
			'Pinehill',
			'Pueblo Viejo',
			'Punta Negra',
			'San Antonio',
			'San Benito Poite',
			'San Felipe',
			'San Jose',
			'San Isidro',
			'San Lucas',
			'San Marcos',
			'San Miguel',
			'San Pablo',
			'San Pedro Columbia',
			'San Vicente',
			'Santa Ana',
			'Santa Cruz',
			'Santa Elena',
			'Santa Teresa',
			'Silver Creek',
			'Sunday Wood',
			'Swasey',
			'Tambran',
			'Trio',
			'Wilson Road',
			'Yemeri Grove'
		],
	},
	distanceToFind: 1200,
	adminBadgeNumber: 'welovit',
	// google_api: 'AIzaSyB2hzpy55dNKYbAmb4f7eFi-mAzk0v6Szo',
	google_api : 'AIzaSyALhybkhM5dNefz73p9GwDZEgSe6Y9sewA',
	districtBoundingBoxes: [
		{
			district_name: "Belize District",
			min_lat: 17.104485952843525,
			max_lat: 17.972288287797685,
			min_lng: -88.64130223736659,
			max_lng: -88.16686020421702,
		},
		{
			district_name: "Corozal District",
			min_lat: 17.959945805874824,
			max_lat: 18.490758819631182,
			min_lng: -88.61405893655497,
			max_lng: -88.08356687928742,
		},
		{
			district_name: "Orange Walk District",
			min_lat: 17.321032147946045,
			max_lat: 18.247028227008503,
			min_lng: -89.16137467773392,
			max_lng: -88.28434729275645,
		},
		{
			district_name: "Cayo District",
			min_lat: 16.39262557809166,
			max_lat: 17.489940555630778,
			min_lng: -89.19313966829063,
			max_lng: -88.54828467468408,
		},
		{
			district_name: "Stann Creek District",
			min_lat: 16.49765812972614,
			max_lat: 17.135768879617217,
			min_lng: -88.77762468393088,
			max_lng: -88.21507727203667,
		},
		{
			district_name: "Toledo District",
			min_lat: 15.879651978131093,
			max_lat: 16.691849700946925,
			min_lng: -89.2365122115767,
			max_lng: -88.38638261939055
		},

	]
}; 